# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Se5QQm5ltWdOFVJIzdCsyaEOeHVD4OTaUDQ1FpotuRwq8POiKpYE0W/O7eax+xyjO1VuXyZxsb0a95KlbMBKS0iW8L9vuLDSVmUXk9tioq67ctNlJW5JScKRkPOUcCKhAsjfE9n2JSPuSDKOrG6hAR2BY/BWrj4qoHEMNdA766sZEI2GRbwx88CT57F7scksvFni4dSGLE25TG+xZ5obB0FSqvm67/Dk9M2G7pgNBXeedizJXW4skDT3IOCjmS7IYRXnAKlzXkZzzPPM2sxxTNS2iaRfbnRHEoN/5t4+GbGxueD8/BgidtOesEHrXrKbhMZuC5hW7qphhUZtPr8UwhqEm/FLE6iUAZqrl5Lqdz1IiqpsTZfJOd5m4oaEB0lgBO8+IZCl9uDPzPnhKpo0+vgVHBN+tOW30bVAwGC+Arc9BB0nG7shPS+tvAhjemrsFwM+jXM56dSIIB9LPdzGE+4JYdaZySkkKym0D7JUUAUPC2aD7olB0Wmu3dAUMxYk1Ql0dEdL7pA84ILZWwFm3edkUcIjXnP6PqBQFjfj4WV/G50bm8Y4XVjLmgtKjpTefIqPvFF96ZTXpPNzoz8DgLI7fBG03RaPCuJoiAVEIvr4CghR/HIwH4qatpCru2+J9AKFW1pv9XFYcIgqiBT9I+9E+yX2nfvY6vYJ9pbh9/U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
