travis:
  secure:
    BINSTAR_TOKEN: x5+IuaqECOzJgvKHZ6hsZ8+v/g1/TwttX4zOfOvLT9fS23s5GTOwoQxupsHlKqJSHkfGF4aZjINlwrLgPKyECMg7l41VY+G0fMGJrWOfhMidARJkQBMeQvrSmp4mkN95QWrNzJsNn5+PfyT7w+9pL0qPnl5SgqyY500kjDRbWu9ds3iR3mF/syu7dixOhCGfvgAnyc5COmGitxvta4hT2iRjrrv3szww6s/uwziDY7Rj8y0H+Y8aIqKVd+AzE6vsj7Lf5fSPdyjiHsl9dJz0zig4vK73aoc4dBOocAmKXh8HlLzpPFN4Sl8k4GqUYZ29UzXxAzKs53z/0/5TIq7CdOjJAbg8E9zqS3xodG8eKbPFHtrSPdZL0lW23Z64mpsqtQQwIXZ0rWKjOiixg9TsMIoQwWef1Oi31xzCW38grL4aik4fVR8aiB+8vwXKIjnj4wdlIKFpqgmuklmc0ywANFnq2af1xq6vgqGK2Yn84/53gS5T2w+iBuhO2o4qLx3KllRbhNtSOz9k7iRcsEzS631GQWDQPQiu27yeL8u/vgL0ltkmEvZdZ8vI1mzoree+X7BNe/ZutXoIl35k/2mcXK2f9qSk9LQzItC7U7zAPgGTxeLesL94X86BWWmagLVfo1XU6AV4/OQDh/AstpP2Q7goh1UCRPkwbMFu7Uw2OoM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
